//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicada
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aplicadaBDEntities : DbContext
    {
        public aplicadaBDEntities()
            : base("name=aplicadaBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<modelo> modelo { get; set; }
        public virtual DbSet<orden> orden { get; set; }
        public virtual DbSet<ordenempleado> ordenempleado { get; set; }
        public virtual DbSet<ordenestado> ordenestado { get; set; }
        public virtual DbSet<ordenservicio> ordenservicio { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<serviciostock> serviciostock { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<tiposervicio> tiposervicio { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
