//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicada
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenservicio
    {
        public int id_ordenservicio { get; set; }
        public int id_orden { get; set; }
        public int id_servicio { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual orden orden { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
