//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicada
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenestado
    {
        public int id_estado { get; set; }
        public int id_orden { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_espera { get; set; }
        public Nullable<System.DateTime> fecha_taller { get; set; }
        public Nullable<System.DateTime> fecha_fintaller { get; set; }
        public Nullable<System.DateTime> fecha_cobrado { get; set; }
        public Nullable<System.DateTime> fecha_entregado { get; set; }
    
        public virtual orden orden { get; set; }
    }
}
